apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestamo-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prestamos
  template:
    metadata:
      labels:
        app: prestamos
    spec:
      containers:
      - name: prestamos
        image: prestamomicroservice.azurecr.io/amiltonr/prestamosmicroservice
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: prestamo-microservice-svc
spec:
  selector:
    app: prestamos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
