// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prestamos.Infrastructure;

#nullable disable

namespace Prestamos.Infrastructure.Migrations
{
    [DbContext(typeof(PrestamosDbContext))]
    partial class PrestamosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prestamos.Domain.Models.PrestamoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int>("IdPrestamoEncabezado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPrestamoEncabezado");

                    b.ToTable("PrestamoDetalles");
                });

            modelBuilder.Entity("Prestamos.Domain.Models.PrestamoEncabezado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioBibliotecario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PrestamoEncabezados");
                });

            modelBuilder.Entity("Prestamos.Domain.Models.PrestamoDetalle", b =>
                {
                    b.HasOne("Prestamos.Domain.Models.PrestamoEncabezado", "PrestamoEncabezado")
                        .WithMany("PrestamoDetalles")
                        .HasForeignKey("IdPrestamoEncabezado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrestamoEncabezado");
                });

            modelBuilder.Entity("Prestamos.Domain.Models.PrestamoEncabezado", b =>
                {
                    b.Navigation("PrestamoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
